image: ubuntu:latest

variables:
  GCC_V: 9
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

stages:
  - build
  - test
  - merge

install:
  stage: build
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - apt-get install -y make
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_SHARE" | tr -d '\r' | ssh-add -
    - echo "$SSH_PRIVATE_KEY_UTIL" | tr -d '\r' | ssh-add -
    - echo "$SSH_PRIVATE_KEY_BATL" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.umich.edu >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - perl -e '$a=`find * -type f -size +1M`; die "Files exceeding 1M size limit $a\n" if $a; exit 0'
    - ./Config.pl -compiler=gfortran -install
  artifacts:
    paths:
      - share
      - util
      - srcBATL
    expire_in: 1 hour

validity:
  stage: test
  before_script:
    - apt-get update -y && apt-get install --yes gcc gfortran g++ make
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes openmpi-bin libopenmpi-dev
    - chmod +x share/Scripts/CheckEmptyFile.sh
  script:
    - ./Config.pl -O0 -compiler=gfortran -install
    - make -j test_hallmhd NP=1
    - ./share/Scripts/CheckEmptyFile.sh test_hallmhd.diff
    
performance:
  stage: test
  before_script:
    - apt-get update -y && apt-get install --yes gcc gfortran g++ make
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes openmpi-bin libopenmpi-dev
    - chmod +x share/Scripts/CheckEmptyFile.sh
  script:
   - ./Config.pl -O4 -compiler=gfortran -install
   - make -j test_hallmhd NP=1
  rules:
    - allow_failure: true

stable:
  stage: merge
  variables:
    DEV_BRANCH: feature-stable-pipeline
  before_script:
    - apt-get update -y && apt-get install --yes git
  rules:
    - if: '$CI_COMMIT_BRANCH == "$DEV_BRANCH"'
    - when: on_success
    - allow_failure: false
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_CI" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.umich.edu >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git fetch origin stable --depth=1
    - git checkout stable && git merge $DEV_BRANCH && git push origin stable

# vim: softtabstop=2 shiftwidth=2
