image: ubuntu:latest

variables:
  GCC_V: 9
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

stages:
  - build
  - test
  - merge

install:
  stage: build
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - apt-get install -y make
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_SHARE" | tr -d '\r' | ssh-add -
    - echo "$SSH_PRIVATE_KEY_UTIL" | tr -d '\r' | ssh-add -
    - echo "$SSH_PRIVATE_KEY_BATL" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - gitlab_hostname=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@||g' | sed -e 's|/.*||g')
    - ssh-keyscan "${gitlab_hostname}" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - perl -e '$a=`find * -type f -size +1M`; die "Files exceeding 1M size limit $a\n" if $a; exit 0'
    - ./Config.pl -compiler=gfortran -install
  artifacts:
    paths:
      - share
      - util
      - srcBATL
    expire_in: 1 hour

validity:
  stage: test
  before_script:
    - apt-get update -y && apt-get install --yes gcc gfortran g++ make
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes openmpi-bin libopenmpi-dev
    - chmod +x share/Scripts/CheckEmptyFile.sh
  script:
    - ./Config.pl -O0 -compiler=gfortran -install
    - make -j test_hallmhd NP=1
    - ./share/Scripts/CheckEmptyFile.sh test_hallmhd.diff
    
performance:
  stage: test
  before_script:
    - apt-get update -y && apt-get install --yes gcc gfortran g++ make
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes openmpi-bin libopenmpi-dev
    - chmod +x share/Scripts/CheckEmptyFile.sh
  script:
   - ./Config.pl -O4 -compiler=gfortran -install
   - make -j test_hallmhd NP=1
  rules:
    - allow_failure: true

# You must create deploy keys in order for this to work.
# If the TARGET_BRANCH is protected the person who *created*
# the deploy keys must have permissions to write.
stable:
  stage: merge
  # Config the branches you want to merge
  variables:
    SOURCE_BRANCH: 'master'
    TARGET_BRANCH: 'stable'
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - apt-get update -y && apt-get install --yes git
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    # change remote to ssh url
    - gitlab_hostname=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@||g' | sed -e 's|/.*||g')
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_CI" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan "${gitlab_hostname}" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  rules:
    - when: never
    - if: '$CI_COMMIT_BRANCH == $SOURCE_BRANCH'
      when: on_success
      allow_failure: false
  script:
    # change remote to ssh url
    - url_host=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@|ssh://git@|g')
    - git remote set-url --push origin "${url_host}"
    - git fetch origin "${TARGET_BRANCH}" --depth=1
    - git checkout "${TARGET_BRANCH}" 
    - git merge origin/"${SOURCE_BRANCH}"
    - git push origin "${TARGET_BRANCH}"

# vim: softtabstop=2 shiftwidth=2
